# Generated by Django 4.2.16 on 2024-10-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=10)),
                ('Company', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=10)),
                ('Town', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('Postcode', models.IntegerField(max_length=10)),
                ('Mobile', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=10)),
            ],
        ),
    ]
