# Generated by Django 4.2.16 on 2024-10-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=10)),
                ('message', models.TextField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='billing',
        ),
    ]
