# Generated by Django 4.2.16 on 2024-10-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_vegetables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vegetables',
        ),
    ]
